<%@ Page Title="Página principal" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="venta._Default" %>

<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
            <h1>productos destacados</h1></hgroup>
            <p>
                &nbsp;</p>
        </div>
    </section>
</asp:Content>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <div class="tab-content" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-weight: normal; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <div class="std" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
            <div class=" jcarousel-skin-products" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                <div class="jcarousel-container jcarousel-container-horizontal" style="border-style: none; border-color: inherit; border-width: 0px; margin: 0px; padding: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; width: 920px; position: relative; display: block; top: 0px; left: 0px; height: 329px;">
                    <div class="jcarousel-clip jcarousel-clip-horizontal" style="margin: 0px 0px 0px 35px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; overflow: hidden; width: 850px; height: 260px; position: relative;">
                        <ul id="tabs-home-carrusel229" class="carousel-tabs jcarousel-list jcarousel-list-horizontal" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; list-style: none; overflow: hidden; position: relative; top: 0px; left: 0px; width: 954px;">
                            <li class="item first jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal" jcarouselindex="1" style="margin: 0px; padding: 10px 15px 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(230, 229, 229); border-bottom-color: initial; border-left-color: initial; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; width: 140px !important; height: 405px; float: left; overflow: hidden; color: rgb(113, 113, 115); list-style: none;">
                                <a class="product-image" href="https://www.dimerc.cl/b2bcl/marcador-perm-desech-sharpie-p-fina-negro.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative; display: block; width: 140px !important; height: 140px !important;" title="">
                                <div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <img alt="MARCADOR PERMANENTE SHARPIE DESECHABLE CUERPO PLASTICO PUNTA FINA NEGRO" height="140" src="https://www.dimerc.cl/media/catalog/product/cache/1/small_image/140x/3ca09046e57efcdb83f1f5d21accf2dc/img_web/l401104.jpg" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; display: block;" width="140" /></a><div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <div class="product-box-name" style="margin: 10px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 60px; overflow: hidden;">
                                    <span class="manufacturer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(113, 113, 115); text-transform: uppercase; display: block; height: 15px; overflow: hidden;">SHARPIE</span><h2 class="product-name" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 13px; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 25px; overflow: hidden;">
                                        <a href="https://www.dimerc.cl/b2bcl/marcador-perm-desech-sharpie-p-fina-negro.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(113, 113, 115); text-decoration: none; position: relative;" title="MARCADOR PERMANENTE SHARPIE DESECHABLE CUERPO PLASTICO PUNTA FINA NEGRO">MARCADOR PERMANENTE SHARPIE DESECHABLE CUERPO PLASTICO PUNTA FINA NEGRO</a></h2>
                                    <span class="sku" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">L401104</span></div>
                                <div class="price-box" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 10px;">
                                    <span id="product-price-15891" class="regular-price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;"><span class="price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 15px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; white-space: nowrap !important; color: rgb(207, 27, 43);">&nbsp;</span><abbr class="tax-info" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(207, 27, 43);"></abbr></span></div>
                                <div class="actions" style="margin: 12px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                    <ul class="add-to-links" style="margin: 5px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; list-style: none;">
                                        <li class="view-details" style="margin: 0px; padding: 0px !important; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; background: none 0px -114px no-repeat;"><a href="https://www.dimerc.cl/b2bcl/marcador-perm-desech-sharpie-p-fina-negro.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative;">Ver detalles</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="item jcarousel-item jcarousel-item-horizontal jcarousel-item-2 jcarousel-item-2-horizontal" jcarouselindex="2" style="margin: 0px; padding: 10px 15px 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(230, 229, 229); border-bottom-color: initial; border-left-color: initial; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; width: 140px !important; height: 405px; float: left; overflow: hidden; color: rgb(113, 113, 115); list-style: none;">
                                <a class="product-image" href="https://www.dimerc.cl/b2bcl/3m-post-it-amarillo-nota-adhesiva-100-hojas.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative; display: block; width: 140px !important; height: 140px !important;" title="">
                                <div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <img alt="NOTA ADHESIVA 3M POST IT 654 BLOCK 100 HOJAS AMARILLO" height="140" src="https://www.dimerc.cl/media/catalog/product/cache/1/small_image/140x/3ca09046e57efcdb83f1f5d21accf2dc/n/o/nota-adhesiva-3m-post-it-654-block-100-hojas-amarillo_1.jpg" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; display: block;" width="140" /></a><div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <div class="product-box-name" style="margin: 10px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 60px; overflow: hidden;">
                                    <span class="manufacturer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(113, 113, 115); text-transform: uppercase; display: block; height: 15px; overflow: hidden;">POST IT</span><h2 class="product-name" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 13px; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 25px; overflow: hidden;">
                                        <a href="https://www.dimerc.cl/b2bcl/3m-post-it-amarillo-nota-adhesiva-100-hojas.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(113, 113, 115); text-decoration: none; position: relative;" title="NOTA ADHESIVA 3M POST IT 654 BLOCK 100 HOJAS AMARILLO">NOTA ADHESIVA 3M POST IT 654 BLOCK 100 HOJAS AMARILLO</a></h2>
                                    <span class="sku" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">H400312</span></div>
                                <div class="price-box" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 10px;">
                                    <span id="product-price-16091" class="regular-price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;"><span class="price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 15px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; white-space: nowrap !important; color: rgb(207, 27, 43);">&nbsp;</span><abbr class="tax-info" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(207, 27, 43);"></abbr></span></div>
                                <div class="actions" style="margin: 12px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                    <ul class="add-to-links" style="margin: 5px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; list-style: none;">
                                        <li class="view-details" style="margin: 0px; padding: 0px !important; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; background: none 0px -114px no-repeat;"><a href="https://www.dimerc.cl/b2bcl/3m-post-it-amarillo-nota-adhesiva-100-hojas.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative;">Ver detalles</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="item jcarousel-item jcarousel-item-horizontal jcarousel-item-3 jcarousel-item-3-horizontal" jcarouselindex="3" style="margin: 0px; padding: 10px 15px 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(230, 229, 229); border-bottom-color: initial; border-left-color: initial; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; width: 140px !important; height: 405px; float: left; overflow: hidden; color: rgb(113, 113, 115); list-style: none;">
                                <a class="product-image" href="https://www.dimerc.cl/b2bcl/toner-hp-q7553a-negro-3-000-pagdatacom.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative; display: block; width: 140px !important; height: 140px !important;" title="">
                                <div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <img alt="TONER HP Q7553A NEGRO 3.000 PAG DIMERC" height="140" src="https://www.dimerc.cl/media/catalog/product/cache/1/small_image/140x/3ca09046e57efcdb83f1f5d21accf2dc/img_web/C883405.jpg" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; display: block;" width="140" /></a><div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <div class="product-box-name" style="margin: 10px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 60px; overflow: hidden;">
                                    <span class="manufacturer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(113, 113, 115); text-transform: uppercase; display: block; height: 15px; overflow: hidden;">HP</span><h2 class="product-name" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 13px; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 25px; overflow: hidden;">
                                        <a href="https://www.dimerc.cl/b2bcl/toner-hp-q7553a-negro-3-000-pagdatacom.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(113, 113, 115); text-decoration: none; position: relative;" title="TONER HP Q7553A NEGRO 3.000 PAG DIMERC">TONER HP Q7553A NEGRO 3.000 PAG DIMERC</a></h2>
                                    <span class="sku" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">C883405</span></div>
                                <div class="price-box" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 10px;">
                                    <span id="product-price-19753" class="regular-price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;"><span class="price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 15px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; white-space: nowrap !important; color: rgb(207, 27, 43);">&nbsp;</span><abbr class="tax-info" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(207, 27, 43);"></abbr></span></div>
                                <div class="actions" style="margin: 12px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                    <ul class="add-to-links" style="margin: 5px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; list-style: none;">
                                        <li class="view-details" style="margin: 0px; padding: 0px !important; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; background: none 0px -114px no-repeat;"><a href="https://www.dimerc.cl/b2bcl/toner-hp-q7553a-negro-3-000-pagdatacom.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative;">Ver detalles</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="item jcarousel-item jcarousel-item-horizontal jcarousel-item-4 jcarousel-item-4-horizontal" jcarouselindex="4" style="margin: 0px; padding: 10px 15px 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(230, 229, 229); border-bottom-color: initial; border-left-color: initial; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; width: 140px !important; height: 405px; float: left; overflow: hidden; color: rgb(113, 113, 115); list-style: none;">
                                <a class="product-image" href="https://www.dimerc.cl/b2bcl/adh-en-barra-40-gr-stic-uhu-rhein.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative; display: block; width: 140px !important; height: 140px !important;" title="">
                                <div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <img alt="ADHESIVO UHU EN BARRA 40 G STICK" height="140" src="https://www.dimerc.cl/media/catalog/product/cache/1/small_image/140x/3ca09046e57efcdb83f1f5d21accf2dc/img_web/U421955.jpg" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; display: block;" width="140" /></a><div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <div class="product-box-name" style="margin: 10px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 60px; overflow: hidden;">
                                    <span class="manufacturer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(113, 113, 115); text-transform: uppercase; display: block; height: 15px; overflow: hidden;">UHU</span><h2 class="product-name" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 13px; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 25px; overflow: hidden;">
                                        <a href="https://www.dimerc.cl/b2bcl/adh-en-barra-40-gr-stic-uhu-rhein.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(113, 113, 115); text-decoration: none; position: relative;" title="ADHESIVO UHU EN BARRA 40 G STICK">ADHESIVO UHU EN BARRA 40 G STICK</a></h2>
                                    <span class="sku" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">U421955</span></div>
                                <div class="price-box" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 10px;">
                                    <span id="product-price-23714" class="regular-price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;"><span class="price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 15px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; white-space: nowrap !important; color: rgb(207, 27, 43);">&nbsp;</span><abbr class="tax-info" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(207, 27, 43);"></abbr></span></div>
                                <div class="actions" style="margin: 12px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                    <ul class="add-to-links" style="margin: 5px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; list-style: none;">
                                        <li class="view-details" style="margin: 0px; padding: 0px !important; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; background: none 0px -114px no-repeat;"><a href="https://www.dimerc.cl/b2bcl/adh-en-barra-40-gr-stic-uhu-rhein.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative;">Ver detalles</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="item last jcarousel-item jcarousel-item-horizontal jcarousel-item-5 jcarousel-item-5-horizontal" jcarouselindex="5" style="margin: 0px; padding: 10px 15px 0px; border: none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; width: 140px !important; height: 405px; float: left; overflow: hidden; color: rgb(113, 113, 115); list-style: none;">
                                <a class="product-image" href="https://www.dimerc.cl/b2bcl/libreta-queen-a6-rhein.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative; display: block; width: 140px !important; height: 140px !important;" title="">
                                <div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <img alt="LIBRETA QUEEN A6 RHEIN" height="140" src="https://www.dimerc.cl/media/catalog/product/cache/1/small_image/140x/3ca09046e57efcdb83f1f5d21accf2dc/u/4/u425042_3.jpg" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; display: block;" width="140" /></a><div class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                </div>
                                <div class="product-box-name" style="margin: 10px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 60px; overflow: hidden;">
                                    <span class="manufacturer" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(113, 113, 115); text-transform: uppercase; display: block; height: 15px; overflow: hidden;">RHEIN</span><h2 class="product-name" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 13px; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 25px; overflow: hidden;">
                                        <a href="https://www.dimerc.cl/b2bcl/libreta-queen-a6-rhein.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(113, 113, 115); text-decoration: none; position: relative;" title="LIBRETA QUEEN A6 RHEIN">LIBRETA QUEEN A6 RHEIN</a></h2>
                                    <span class="sku" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">U425042</span></div>
                                <div class="price-box" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; height: 10px;">
                                    <span id="product-price-24079" class="regular-price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;"><span class="price" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 15px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; white-space: nowrap !important; color: rgb(207, 27, 43);">&nbsp;</span><abbr class="tax-info" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 11px; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(207, 27, 43);"></abbr></span></div>
                                <div class="actions" style="margin: 12px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif;">
                                    <ul class="add-to-links" style="margin: 5px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; list-style: none;">
                                        <li class="view-details" style="margin: 0px; padding: 0px !important; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; background: none 0px -114px no-repeat;"><a href="https://www.dimerc.cl/b2bcl/libreta-queen-a6-rhein.html" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; vertical-align: baseline; font-family: &quot;Open Sans&quot;, sans-serif; transition: color 0.5s; color: rgb(207, 27, 43); text-decoration: none; position: relative;">Ver detalles</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <br />
                    <br />
                </div>
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
    <p>
        &nbsp;</p>
</asp:Content>
